const char* gc_szSCPD =

"<?xml version=\"1.0\"?>"
"<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">"
"  <specVersion>"
"    <major>1</major>"
"    <minor>0</minor>"   
"  </specVersion>"
" <actionList>"

"    <action>"
"      <name>ControlDevice</name>"
"	  <argumentList>"
"		<argument>"
"			<name>ControlRequest</name>"
"			<direction>in</direction>"
"			<relatedStateVariable>A_ARG_TYPE_ControlRequest</relatedStateVariable>"
"		</argument>"
"		<argument>"
"			<name>ControlResponse</name>"
"			<direction>out</direction>"
"			<relatedStateVariable>A_ARG_TYPE_ControlResponse</relatedStateVariable>"
"		</argument>"
"	  </argumentList>"
"    </action>"

"    <action>"
"      <name>StartMonkeyTest</name>"
"	  <argumentList>"
"		<argument>"
"			<name>MonkeyParams</name>"
"			<direction>in</direction>"
"			<relatedStateVariable>A_ARG_TYPE_MonkeyParams</relatedStateVariable>"
"		</argument>"
"	  </argumentList>"
"    </action>"

"    <action>"
"      <name>StartTestController</name>"
"	  <argumentList>"
"		<argument>"
"			<name>MultiScriptParams</name>"
"			<direction>in</direction>"
"			<relatedStateVariable>A_ARG_TYPE_MultiScriptParams</relatedStateVariable>"
"		</argument>"
"	  </argumentList>"
"    </action>"

"    <action>"
"      <name>GetDeviceStatus</name>"
"	  <argumentList>"
"		<argument>"
"			<name>DeviceStatus</name>"
"			<direction>out</direction>"
"			<relatedStateVariable>A_ARG_TYPE_DeviceStatus</relatedStateVariable>"
"		</argument>"
"	  </argumentList>"
"    </action>"

"    <action>"
"      <name>GetLogNums</name>"
"	  <argumentList>"
"		<argument>"
"			<name>LogIDString</name>"
"			<direction>out</direction>"
"			<relatedStateVariable>A_ARG_TYPE_LogIDString</relatedStateVariable>"
"		</argument>"
"	  </argumentList>"
"    </action>"

"    <action>"
"      <name>InvokeScript</name>"
"	  <argumentList>"
"		<argument>"
"			<name>ScriptParameters</name>"
"			<direction>in</direction>"
"			<relatedStateVariable>A_ARG_TYPE_ScriptParameters</relatedStateVariable>"
"		</argument>"
"	  </argumentList>"
"    </action>"

"    <action>"
"      <name>LogDebugOutput</name>"
"	  <argumentList>"
"		<argument>"
"			<name>DebugFile</name>"
"			<direction>in</direction>"
"			<relatedStateVariable>A_ARG_TYPE_DebugFile</relatedStateVariable>"
"		</argument>"
"	  </argumentList>"
"    </action>"

"	<action>"
"	  <name>StartNetDebug</name>"
"	 <argumentList>"
"	   <argument>"
"		   <name>Server</name>"
"		   <direction>in</direction>"
"		   <relatedStateVariable>A_ARG_TYPE_Server</relatedStateVariable>"
"	   </argument>"
"	 </argumentList>"
"	</action>"

"    <action>"
"      <name>InvokeFunction</name>"
"	  <argumentList>"
"		<argument>"
"			<name>FunctionName</name>"
"			<direction>in</direction>"
"			<relatedStateVariable>A_ARG_TYPE_FunctionName</relatedStateVariable>"
"		</argument>"
"	  </argumentList>"
"    </action>"

"    <action>"
"      <name>InstantMessage</name>"
"	  <argumentList>"
"		<argument>"
"			<name>Message</name>"
"			<direction>in</direction>"
"			<relatedStateVariable>A_ARG_TYPE_Message</relatedStateVariable>"
"		</argument>"
"	  </argumentList>"
"    </action>"


"    <action>"
"      <name>StopTestStimulator</name>"
"    </action>"

"    <action>"
"      <name>StopDebugLog</name>"
"    </action>"

"    <action>"
"      <name>StopNetDebug</name>"
"    </action>"

"    <action>"
"      <name>StartEventLogging</name>"
"    </action>"

"    <action>"
"      <name>StopEventLogging</name>"
"    </action>"

"    <action>"
"      <name>DeleteLogDir</name>"
"    </action>"

"  </actionList>"

"  <serviceStateTable>"
"    <stateVariable sendEvents=\"no\">"
"      <name>A_ARG_TYPE_MonkeyParams</name>"
"      <dataType>string</dataType>"
"    </stateVariable>"

"    <stateVariable sendEvents=\"no\">"
"      <name>A_ARG_TYPE_ControlRequest</name>"
"      <dataType>string</dataType>"
"    </stateVariable>"

"    <stateVariable sendEvents=\"no\">"
"      <name>A_ARG_TYPE_ControlResponse</name>"
"      <dataType>string</dataType>"
"    </stateVariable>"

"    <stateVariable sendEvents=\"no\">"
"      <name>A_ARG_TYPE_MultiScriptParams</name>"
"      <dataType>string</dataType>"
"    </stateVariable>"

"    <stateVariable sendEvents=\"no\">"
"      <name>A_ARG_TYPE_DeviceStatus</name>"
"      <dataType>string</dataType>"
"    </stateVariable>"

"    <stateVariable sendEvents=\"no\">"
"      <name>A_ARG_TYPE_LogIDString</name>"
"      <dataType>string</dataType>"
"    </stateVariable>"

"    <stateVariable sendEvents=\"no\">"
"      <name>A_ARG_TYPE_ScriptParameters</name>"
"      <dataType>string</dataType>"
"    </stateVariable>"

"    <stateVariable sendEvents=\"no\">"
"      <name>A_ARG_TYPE_DebugFile</name>"
"      <dataType>string</dataType>"
"    </stateVariable>"

"    <stateVariable sendEvents=\"no\">"
"      <name>A_ARG_TYPE_Server</name>"
"      <dataType>string</dataType>"
"    </stateVariable>"

"    <stateVariable sendEvents=\"no\">"
"      <name>A_ARG_TYPE_FunctionName</name>"
"      <dataType>string</dataType>"
"    </stateVariable>"

"    <stateVariable sendEvents=\"no\">"
"      <name>A_ARG_TYPE_Message</name>"
"      <dataType>string</dataType>"
"    </stateVariable>"


"  </serviceStateTable>"
"</scpd>";
