#ifndef CYGONCE_PKGCONF_NET_H
#define CYGONCE_PKGCONF_NET_H
/*
 * File <pkgconf/net.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGPKG_NET_DRIVER_FRAMEWORK 1
#define CYGPKG_NET_DRIVER_FRAMEWORK_1
#define CYGPKG_NET_API_FILEIO 1
#define INET 1
#define CYGPKG_NET_TFTP 1
#define CYGPKG_NET_TFTPD_THREAD_PRIORITY 10
#define CYGPKG_NET_TFTPD_THREAD_PRIORITY_10
#define CYGPKG_NET_TFTP_FILE_ACCESS 1
#define CYGPKG_NET_DNSCLIENT 1
#define CYGPKG_NET_DNSC_CACHE 1
#define CYGPKG_NET_DNSC_CACHE_TABLE_SIZE 10
#define CYGPKG_NET_DNSC_CACHE_TABLE_SIZE_10
#define CYGPKG_NET_DHCP 1
#define CYGOPT_NET_DHCP_DHCP_THREAD 1
#define CYGOPT_NET_DHCP_DHCP_THREAD_PARAM 1
#define CYGOPT_NET_DHCP_DHCP_THREAD_PARAM_1
#define CYGPKG_NET_DHCP_THREAD_PRIORITY 8
#define CYGPKG_NET_DHCP_THREAD_PRIORITY_8
#define CYGPKG_NET_THREAD_PRIORITY 7
#define CYGPKG_NET_THREAD_PRIORITY_7
#define CYGPKG_NET_FAST_THREAD_PRIORITY 6
#define CYGPKG_NET_FAST_THREAD_PRIORITY_6
#define CYGPKG_NET_NBPF 0
#define CYGPKG_NET_NBPF_0
#define NBPFILTER 0
#define NBPFILTER_0
#define CYGINT_NET_BRIDGE_HANDLER 0
#define CYGINT_NET_BRIDGE_HANDLER_0
#define NBRIDGE 0
#define NBRIDGE_0
#define CYGPKG_NET_NGIF 0
#define CYGPKG_NET_NGIF_0
#define NGIF 0
#define NGIF_0
#define CYGPKG_NET_NLOOP 1
#define CYGPKG_NET_NLOOP_1
#define NLOOP 1
#define NLOOP_1
#define CYGPKG_NET_MEM_USAGE 262144
#define CYGPKG_NET_MEM_USAGE_262144
#define CYGPKG_NET_NUM_WAKEUP_EVENTS 8
#define CYGPKG_NET_NUM_WAKEUP_EVENTS_8
#define CYGHWR_NET_DRIVERS 1
#define CYGHWR_NET_DRIVERS_1
#define CYGHWR_NET_DRIVER_ETH0 1
#define CYGHWR_NET_DRIVER_ETH0_1
#define CYGHWR_NET_DRIVER_ETH0_BOOTP 1
#define CYGHWR_NET_DRIVER_ETH0_DHCP 1
#define CYGHWR_NET_DRIVER_ETH0_BOOTP_SHOW 1
#define CYGHWR_NET_DRIVER_ETH1 0
#define CYGHWR_NET_DRIVER_ETH1_0

#endif
