#ifndef CYGONCE_PKGCONF_HAL_ARM_EDB7XXX_H
#define CYGONCE_PKGCONF_HAL_ARM_EDB7XXX_H
/*
 * File <pkgconf/hal_arm_edb7xxx.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGHWR_HAL_ARM_EDB7XXX_VARIANT EP7312
#define CYGHWR_HAL_ARM_EDB7XXX_VARIANT_EP7312

#ifdef CYGHWR_HAL_ARM_EDB7XXX_VARIANT_CL_PS7111
#define HAL_PLATFORM_CPU    "ARM 710C"
#define HAL_PLATFORM_BOARD  "Cirrus Logic CL-PS7111"
#define HAL_PLATFORM_EXTRA  ""
#endif //CYGHWR_HAL_ARM_EDB7XXX_VARIANT_CL_PS7111

#ifdef CYGHWR_HAL_ARM_EDB7XXX_VARIANT_EP7209
#define HAL_PLATFORM_CPU    "ARM 720T"
#define HAL_PLATFORM_BOARD  "Cirrus Logic EDB7209"
#define HAL_PLATFORM_EXTRA  ""
#endif //CYGHWR_HAL_ARM_EDB7XXX_VARIANT_EP7209

#ifdef CYGHWR_HAL_ARM_EDB7XXX_VARIANT_EP7211
#define HAL_PLATFORM_CPU    "ARM 720T"
#define HAL_PLATFORM_BOARD  "Cirrus Logic EDB7211"
#define HAL_PLATFORM_EXTRA  ""
#endif //CYGHWR_HAL_ARM_EDB7XXX_VARIANT_EP7211

#ifdef CYGHWR_HAL_ARM_EDB7XXX_VARIANT_EP7212
#define HAL_PLATFORM_CPU    "ARM 720T"
#define HAL_PLATFORM_BOARD  "Cirrus Logic EDB7212"
#define HAL_PLATFORM_EXTRA  ""
#endif //CYGHWR_HAL_ARM_EDB7XXX_VARIANT_EP7212

#ifdef CYGHWR_HAL_ARM_EDB7XXX_VARIANT_EP7312
#define HAL_PLATFORM_CPU    "ARM 720T"
#define HAL_PLATFORM_BOARD  "Cirrus Logic EDB7312"
#define HAL_PLATFORM_EXTRA  ""
#endif //CYGHWR_HAL_ARM_EDB7XXX_VARIANT_EP7312

#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD 115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD_115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD 115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD_115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 2
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_2
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT_0
#define CYGHWR_HAL_ARM_EDB7XXX_PROCESSOR_CLOCK 73728
#define CYGHWR_HAL_ARM_EDB7XXX_PROCESSOR_CLOCK_73728
#define CYGHWR_HAL_ARM_EDB7XXX_DRAM_SIZE 16
#define CYGHWR_HAL_ARM_EDB7XXX_DRAM_SIZE_16
#define CYGHWR_HAL_ARM_EDB7XXX_LCD_INSTALLED 1
#define CYGHWR_HAL_ARM_EDB7XXX_DEBUG_STARTUP 1
#define CYGNUM_HAL_RTC_CONSTANTS 1
#define CYGNUM_HAL_RTC_NUMERATOR 1000000000
#define CYGNUM_HAL_RTC_NUMERATOR_1000000000
#define CYGNUM_HAL_RTC_DENOMINATOR 100
#define CYGNUM_HAL_RTC_DENOMINATOR_100
#define CYGNUM_HAL_RTC_PERIOD 5120
#define CYGNUM_HAL_RTC_PERIOD_5120
#define CYGBLD_GLOBAL_OPTIONS 1
#define CYGPKG_HAL_ARM_EDB7XXX_OPTIONS 1
#define CYGSEM_HAL_USE_ROM_MONITOR GDB_stubs
#define CYGSEM_HAL_USE_ROM_MONITOR_GDB_stubs

#endif
