#ifndef CYGONCE_PKGCONF_UITRON_H
#define CYGONCE_PKGCONF_UITRON_H
/*
 * File <pkgconf/uitron.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

/***** proc output start *****/
#include <pkgconf/system.h>
#include <pkgconf/kernel.h>
/*****  proc output end  *****/
#define CYGINT_UITRON_CONFORMANCE 1
#define CYGINT_UITRON_CONFORMANCE_1
#define CYGIMP_UITRON_LOOSE_CONFORMANCE 1
#define CYGSEM_UITRON_BAD_PARAMS_RETURN_ERRORS 1
#define CYGPKG_UITRON_SEMAS 1
#define CYGNUM_UITRON_SEMAS 3
#define CYGNUM_UITRON_SEMAS_3
#define CYGPKG_UITRON_SEMAS_CREATE_DELETE 1
#define CYGNUM_UITRON_SEMAS_INITIALLY 3
#define CYGNUM_UITRON_SEMAS_INITIALLY_3
#define CYGPKG_UITRON_MBOXES 1
#define CYGNUM_UITRON_MBOXES 4
#define CYGNUM_UITRON_MBOXES_4
#define CYGPKG_UITRON_MBOXES_CREATE_DELETE 1
#define CYGNUM_UITRON_MBOXES_INITIALLY 4
#define CYGNUM_UITRON_MBOXES_INITIALLY_4
#define CYGPKG_UITRON_FLAGS 1
#define CYGNUM_UITRON_FLAGS 5
#define CYGNUM_UITRON_FLAGS_5
#define CYGPKG_UITRON_FLAGS_CREATE_DELETE 1
#define CYGNUM_UITRON_FLAGS_INITIALLY 5
#define CYGNUM_UITRON_FLAGS_INITIALLY_5
#define CYGPKG_UITRON_TASKS 1
#define CYGNUM_UITRON_TASKS 4
#define CYGNUM_UITRON_TASKS_4
#define CYGNUM_UITRON_START_TASKS 1
#define CYGNUM_UITRON_START_TASKS_1
#define CYGPKG_UITRON_TASKS_CREATE_DELETE 1
#define CYGNUM_UITRON_TASKS_INITIALLY 4
#define CYGNUM_UITRON_TASKS_INITIALLY_4
#define CYGNUM_UITRON_STACK_SIZE 2048
#define CYGNUM_UITRON_STACK_SIZE_2048
#define CYGDAT_UITRON_TASK_EXTERNS extern "C" void task1( unsigned int ); \
 extern "C" void task2( unsigned int ); \
 extern "C" void task3( unsigned int ); \
 extern "C" void task4( unsigned int ); \
 static char stack1[ CYGNUM_UITRON_STACK_SIZE ], \
 stack2[ CYGNUM_UITRON_STACK_SIZE ], \
 stack3[ CYGNUM_UITRON_STACK_SIZE ], \
 stack4[ CYGNUM_UITRON_STACK_SIZE ];
#define CYGDAT_UITRON_TASK_INITIALIZERS CYG_UIT_TASK( "t1", 1, task1, &stack1, CYGNUM_UITRON_STACK_SIZE ), \
 CYG_UIT_TASK( "t2", 2, task2, &stack2, CYGNUM_UITRON_STACK_SIZE ), \
 CYG_UIT_TASK( "t3", 3, task3, &stack3, CYGNUM_UITRON_STACK_SIZE ), \
 CYG_UIT_TASK( "t4", 4, task4, &stack4, CYGNUM_UITRON_STACK_SIZE ),
#define CYGPKG_UITRON_MEMPOOLFIXED 1
#define CYGNUM_UITRON_MEMPOOLFIXED 3
#define CYGNUM_UITRON_MEMPOOLFIXED_3
#define CYGPKG_UITRON_MEMPOOLFIXED_CREATE_DELETE 1
#define CYGNUM_UITRON_MEMPOOLFIXED_INITIALLY 3
#define CYGNUM_UITRON_MEMPOOLFIXED_INITIALLY_3
#define CYGDAT_UITRON_MEMPOOLFIXED_EXTERNS static char fpool1[ 2000 ], \
 fpool2[ 2000 ], \
 fpool3[ 2000 ];
#define CYGDAT_UITRON_MEMPOOLFIXED_INITIALIZERS CYG_UIT_MEMPOOLFIXED( fpool1, 2000,  20 ), \
 CYG_UIT_MEMPOOLFIXED( fpool2, 2000, 100 ), \
 CYG_UIT_MEMPOOLFIXED( fpool3, 2000, 500 ),
#define CYGPKG_UITRON_MEMPOOLVAR 1
#define CYGNUM_UITRON_MEMPOOLVAR 3
#define CYGNUM_UITRON_MEMPOOLVAR_3
#define CYGPKG_UITRON_MEMPOOLVAR_CREATE_DELETE 1
#define CYGNUM_UITRON_MEMPOOLVAR_INITIALLY 3
#define CYGNUM_UITRON_MEMPOOLVAR_INITIALLY_3
#define CYGDAT_UITRON_MEMPOOLVAR_EXTERNS static char vpool1[ 2000 ], \
 vpool2[ 2000 ], \
 vpool3[ 2000 ];
#define CYGDAT_UITRON_MEMPOOLVAR_INITIALIZERS CYG_UIT_MEMPOOLVAR( vpool1, 2000 ), \
 CYG_UIT_MEMPOOLVAR( vpool2, 2000 ), \
 CYG_UIT_MEMPOOLVAR( vpool3, 2000 ),
#define CYGPKG_UITRON_ALARMS 1
#define CYGNUM_UITRON_ALARMS 3
#define CYGNUM_UITRON_ALARMS_3
#define CYGPKG_UITRON_CYCLICS 1
#define CYGNUM_UITRON_CYCLICS 3
#define CYGNUM_UITRON_CYCLICS_3
#define CYGPKG_UITRON_INTERRUPT_FUNCTIONS 1
#define CYGSEM_UITRON_ISRFUNCS_TRY_IMMEDIATE_EXECUTION 1
#define CYGNUM_UITRON_ISR_ACTION_QUEUESIZE 32
#define CYGNUM_UITRON_ISR_ACTION_QUEUESIZE_32
#define CYGPKG_UITRON_VERSION 1
#define CYGNUM_UITRON_VER_MAKER 0
#define CYGNUM_UITRON_VER_MAKER_0
#define CYGNUM_UITRON_VER_ID 0
#define CYGNUM_UITRON_VER_ID_0
#define CYGNUM_UITRON_VER_SPVER 0x00005302
#define CYGNUM_UITRON_VER_SPVER_0x00005302
#define CYGNUM_UITRON_VER_PRVER 0x00000100
#define CYGNUM_UITRON_VER_PRVER_0x00000100
#define CYGPKG_UITRON_VERSION_PRNO 1
#define CYGNUM_UITRON_VER_PRNO_0 0
#define CYGNUM_UITRON_VER_PRNO_0_0
#define CYGNUM_UITRON_VER_PRNO_1 0
#define CYGNUM_UITRON_VER_PRNO_1_0
#define CYGNUM_UITRON_VER_PRNO_2 0
#define CYGNUM_UITRON_VER_PRNO_2_0
#define CYGNUM_UITRON_VER_PRNO_3 0
#define CYGNUM_UITRON_VER_PRNO_3_0
#define CYGNUM_UITRON_VER_CPU 0
#define CYGNUM_UITRON_VER_CPU_0
#define CYGNUM_UITRON_VER_VAR 0x00008000
#define CYGNUM_UITRON_VER_VAR_0x00008000
#define CYGPKG_UITRON_OPTIONS 1

#endif
