#ifndef CYGONCE_PKGCONF_HAL_H
#define CYGONCE_PKGCONF_HAL_H
/*
 * File <pkgconf/hal.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

/***** proc output start *****/
#include <pkgconf/system.h>
#include CYGBLD_HAL_TARGET_H
#ifdef   CYGBLD_HAL_VARIANT_H
#include CYGBLD_HAL_VARIANT_H
#endif
#include CYGBLD_HAL_PLATFORM_H
/****** proc output end ******/
#define CYGPKG_HAL_COMMON 1
#define CYGFUN_HAL_COMMON_KERNEL_SUPPORT 1
#define CYGPKG_HAL_EXCEPTIONS 1
#define CYGSEM_HAL_INSTALL_MMU_TABLES 1
#define CYGPKG_HAL_COMMON_INTERRUPTS 1
#define CYGIMP_HAL_COMMON_INTERRUPTS_USE_INTERRUPT_STACK 1
#define CYGNUM_HAL_COMMON_INTERRUPTS_STACK_SIZE 4096
#define CYGNUM_HAL_COMMON_INTERRUPTS_STACK_SIZE_4096
#define CYGDBG_HAL_COMMON_INTERRUPTS_SAVE_MINIMUM_CONTEXT 1
#define CYGPKG_HAL_COMMON_CONTEXT 1
#define CYGDBG_HAL_COMMON_CONTEXT_SAVE_MINIMUM 1
#define CYGPKG_HAL_DEBUG 1
#define CYGDBG_HAL_DEBUG_GDB_CTRLC_SUPPORT 1
#define CYGDBG_HAL_DEBUG_GDB_THREAD_SUPPORT 1
#define CYGSEM_HAL_VIRTUAL_VECTOR_SUPPORT 1
#define CYGSEM_HAL_VIRTUAL_VECTOR_INHERIT_CONSOLE 1
#define CYGSEM_HAL_VIRTUAL_VECTOR_CLAIM_DEFAULT 1
#define CYGSEM_HAL_VIRTUAL_VECTOR_CLAIM_ICTRL 1
#define CYGSEM_HAL_VIRTUAL_VECTOR_CLAIM_RESET 1
#define CYGSEM_HAL_VIRTUAL_VECTOR_CLAIM_DELAY_US 1
#define CYGSEM_HAL_VIRTUAL_VECTOR_CLAIM_CACHE 1
#define CYGSEM_HAL_VIRTUAL_VECTOR_CLAIM_DATA 1
#define CYGSEM_HAL_VIRTUAL_VECTOR_DIAG 1
#define CYGINT_HAL_PLF_IF_INIT 0
#define CYGINT_HAL_PLF_IF_INIT_0

#endif
