#ifndef CYGONCE_PKGCONF_IO_USB_SLAVE_MASS_STORAGE_H
#define CYGONCE_PKGCONF_IO_USB_SLAVE_MASS_STORAGE_H
/*
 * File <pkgconf/io_usb_slave_mass_storage.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGPKG_IO_USB_SLAVE_MASS_STORAGE_DEVICE MMC
#define CYGPKG_IO_USB_SLAVE_MASS_STORAGE_DEVICE_MMC
#define CYGPKG_IO_USB_SLAVE_MASS_STORAGE_THREAD_PRIORITY 10
#define CYGPKG_IO_USB_SLAVE_MASS_STORAGE_THREAD_PRIORITY_10
#define CYGPKG_IO_USB_SLAVE_MASS_STORAGE_THREAD_STACK_SIZE 4096
#define CYGPKG_IO_USB_SLAVE_MASS_STORAGE_THREAD_STACK_SIZE_4096
#define CYGPKG_IO_USB_MASS_STORAGE_OPTIONS 1

#endif
